FROM node:22-alpine3.18

# Set working directory
WORKDIR /app

# Expose the listening port
EXPOSE 3000

# Run npm start script when container starts
CMD ["sh", "-c", "NODE_ENV=production npm run start"]